function run_coh
% run_master
%
% Script which sets up parameters and then calls master. Please
% make a local copy of this script.
%
% THIS MASTER RUNS FROM THE PARAM GENERATED BY read_param_xls.m,
% which reads in an excel spread sheet
% (e.g. RADAR_param_YYYY_Mission_Aircraft.xls).
%
% Authors: Brady Maasen, John Paden
%
% See also: master, read_param_xls

%error('Copy this script locally, comment this line, and then run.\n');

% =====================================================================
% User Settings
% =====================================================================
%clear; % Optional
%close all; % Optional

params = read_param_xls(ct_filename_param('/users/manjish/Documents/MATLAB/rds_param_2012_Greenland_P333.xls'),'',{'analysis_IceBedCoherenceIndex','analysis'});


clear('param_override');
param_override = [];

%param_override.sched.type='custom_torque';
param_override.sched.type = 'no scheduler';
param_override.sched.cluster_size = Inf;
param_override.sched.rerun_only = false;
param_override.sched.submit_arguments    = '-l nodes=1:ppn=1, walltime=60:00';
%param_override.sched.stop_on_fail = true;
global gRadar;
if exist('param_override','var')
  param_override = merge_structs(gRadar,param_override);
else
  param_override = gRadar;
end

get_coh(params,param_override);

return;
